In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('iphone.csv')

In [3]:
df.head(10)

,Product Name,Product URL,Brand,Sale Price,Mrp,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,NaN,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB
5,"APPLE iPhone 8 Plus (Silver, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,49900,49900,3431,356,MOBEXRGVQGYYP8FV,4.6,2 GB
6,"APPLE iPhone 8 Plus (Space Grey, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,49900,49900,3431,356,MOBEXRGVQKBREZP8,4.6,2 GB
7,"APPLE iPhone 8 (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-space-...,Apple,77000,77000,11202,794,MOBEXRGVZFZGZEWV,4.5,2 GB
8,"APPLE iPhone XS Max (Silver, 64 GB)",https://www.flipkart.com/apple-iphone-xs-max-s...,Apple,89900,89900,1454,149,MOBF944E2XAHW8V5,4.6,4 GB
9,"Apple iPhone XR (RED, 128 GB)",https://www.flipkart.com/apple-iphone-xr-produ...,Apple,41999,52900,79512,6796,MOBF9Z7ZHQC23PWQ,4.6,4 GB

In [4]:
df.shape

(62, 10)

In [6]:
df.dtypes

Product Name          object
Product URL           object
Brand                 object
Sale Price             int64
Mrp                    int64
Number Of Ratings      int64
Number Of Reviews      int64
Upc                   object
Star Rating          float64
Ram                   object
dtype: object

In [14]:
#1 - The column names have spaces . rename the column names to have underscore '_' instead of space 
# (try to do in one go instead of specifying each column name in rename method)

#Use the df.rename() function and refer the columns to be renamed. Not all the columns have to be renamed:
df = df.rename(columns={'Product Name': 'product_name', 'Product URL': 'product_url', 'Brand': 'brand','Sale Price': 'sale_price', 'Mrp': 'mrp', 
                      'Number Of Ratings': 'number_of_ratings','Number Of Reviews': 'number_of_reviews', 'Upc':'upc', 
                      'Star Rating': 'star_rating', 'Ram' : 'ram'}) 
#df.columns = df.columns.str.replace('product_name ','product_url','brand', 'upc', 'RAM')
# this method gives error in lot of conditions

In [15]:
df.columns

Index(['product_name', 'product_url', 'brand', 'sale_price', 'mrp',
       'number_of_ratings', 'number_of_reviews', 'upc', 'star_rating', 'ram'],
      dtype='object')

In [16]:
#2- start rating for some of the models is missing in the dataset.
# fill those missing values with the average rating all the models.

df.describe

<bound method NDFrame.describe of                                 product_name  \
0          APPLE iPhone 8 Plus (Gold, 64 GB)
1   APPLE iPhone 8 Plus (Space Grey, 256 GB)
2       APPLE iPhone 8 Plus (Silver, 256 GB)
3            APPLE iPhone 8 (Silver, 256 GB)
4              APPLE iPhone 8 (Gold, 256 GB)
..                                       ...
57            APPLE iPhone SE (Black, 64 GB)
58           APPLE iPhone 11 (Purple, 64 GB)
59            APPLE iPhone 11 (White, 64 GB)
60            APPLE iPhone 11 (Black, 64 GB)
61              APPLE iPhone 11 (Red, 64 GB)

                                          product_url  brand  sale_price  \
0   https://www.flipkart.com/apple-iphone-8-plus-g...  Apple       49900
1   https://www.flipkart.com/apple-iphone-8-plus-s...  Apple       84900
2   https://www.flipkart.com/apple-iphone-8-plus-s...  Apple       84900
3   https://www.flipkart.com/apple-iphone-8-silver...  Apple       77000
4   https://www.flipkart.com/apple-iphone-8-gold-2...  Apple       77000
..                                                ...    ...         ...
57  https://www.flipkart.com/apple-iphone-se-black...  Apple       29999
58  https://www.flipkart.com/apple-iphone-11-purpl...  Apple       46999
59  https://www.flipkart.com/apple-iphone-11-white...  Apple       46999
60  https://www.flipkart.com/apple-iphone-11-black...  Apple       46999
61  https://www.flipkart.com/apple-iphone-11-red-6...  Apple       46999

      mrp  number_of_ratings  number_of_reviews               upc  \
0   49900               3431                356  MOBEXRGV7EHHTGUH
1   84900               3431                356  MOBEXRGVAC6TJT4F
2   84900               3431                356  MOBEXRGVGETABXWZ
3   77000              11202                794  MOBEXRGVMZWUHCBA
4   77000              11202                794  MOBEXRGVPK7PFEJZ
..    ...                ...                ...               ...
57  39900              95909               8161  MOBFWQ6BR3MK7AUG
58  54900              43470               3331  MOBFWQ6BTFFJKGKE
59  54900              43470               3331  MOBFWQ6BVWVEH3XE
60  54900              43470               3331  MOBFWQ6BXGJCEYNY
61  54900              43470               3331  MOBFWQ6BYYV3FCU7

    star_rating   ram
0           4.6  2 GB
1           4.6  2 GB
2           4.6  2 GB
3           NaN  2 GB
4           4.5  2 GB
..          ...   ...
57          4.5  4 GB
58          4.6  4 GB
59          4.6  4 GB
60          4.6  4 GB
61          4.6  4 GB

[62 rows x 10 columns]>

In [19]:
#2- star rating for some of the models is missing in the dataset.
# fill those missing values with the average rating all the models.

df.loc[:,'star_rating']
df.loc[:,'star_rating'].head(10)

0    4.6
1    4.6
2    4.6
3    NaN
4    4.5
5    4.6
6    4.6
7    4.5
8    4.6
9    4.6
Name: star_rating, dtype: float64

In [21]:
# Calculate the average rating excluding None (missing values)
average_rating = df['star_rating'].mean(skipna=True)

In [23]:
# Fill missing values with the calculated average rating
df['star_rating'].fillna(average_rating, inplace=True)

In [24]:
# Display the modified DataFrame
df

,product_name,product_url,brand,sale_price,mrp,number_of_ratings,number_of_reviews,upc,star_rating,ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.600000,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.600000,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.600000,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,4.576271,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.500000,2 GB
...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.500000,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,43470,3331,MOBFWQ6BTFFJKGKE,4.600000,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,43470,3331,MOBFWQ6BVWVEH3XE,4.600000,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,43470,3331,MOBFWQ6BXGJCEYNY,4.600000,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,43470,3331,MOBFWQ6BYYV3FCU7,4.600000,4 GB

In [25]:
df.loc[:,'star_rating'].head(10)

0    4.600000
1    4.600000
2    4.600000
3    4.576271
4    4.500000
5    4.600000
6    4.600000
7    4.500000
8    4.600000
9    4.600000
Name: star_rating, dtype: float64