In [36]:
import pandas as pd

In [37]:
df = pd.read_csv('iphone.csv')

In [38]:
df.head(2)

,Product Name,Product URL,Brand,Sale Price,Mrp,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB

In [47]:
#12- which iphone has 3rd highest MRP

df.sort_values(by = 'Mrp', ascending = False, inplace = True)

In [48]:
df.head(4)

,Product Name,Product URL,Brand,Sale Price,Mrp,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
41,"APPLE iPhone 12 Pro (Pacific Blue, 512 GB)",https://www.flipkart.com/apple-iphone-12-pro-p...,Apple,140900,149900,545,42,MOBFWBYZTHSXKMGW,4.5,4 GB
24,"APPLE iPhone 12 Pro (Silver, 512 GB)",https://www.flipkart.com/apple-iphone-12-pro-s...,Apple,140900,149900,542,42,MOBFWBYZ5UY6ZBVA,4.5,4 GB
19,"APPLE iPhone 11 Pro (Space Grey, 512 GB)",https://www.flipkart.com/apple-iphone-11-pro-s...,Apple,117900,140300,7088,523,MOBFKCTSRTHRQTFT,4.6,4 GB
21,"APPLE iPhone 11 Pro (Midnight Green, 512 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,117900,140300,7088,523,MOBFKCTSSJCWYGCC,4.6,4 GB

In [44]:
df.loc[3]

Product Name                           APPLE iPhone 8 (Silver, 256 GB)
Product URL          https://www.flipkart.com/apple-iphone-8-silver...
Brand                                                            Apple
Sale Price                                                       77000
Mrp                                                              77000
Number Of Ratings                                                11202
Number Of Reviews                                                  794
Upc                                                   MOBEXRGVMZWUHCBA
Star Rating                                                        NaN
Ram                                                               2 GB
Name: 3, dtype: object

In [45]:
#12- which iphone has 3rd highest MRP

sorted_df = df.sort_values(by = 'Mrp', ascending = False).reset_index(drop= True)

In [46]:
sorted_df                                      #index is resetted this time which don't happen when we have done inplace = True
                                               #inplace = True just sorted the order but don't change the index

,Product Name,Product URL,Brand,Sale Price,Mrp,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 12 Pro (Pacific Blue, 512 GB)",https://www.flipkart.com/apple-iphone-12-pro-p...,Apple,140900,149900,545,42,MOBFWBYZTHSXKMGW,4.5,4 GB
1,"APPLE iPhone 12 Pro (Silver, 512 GB)",https://www.flipkart.com/apple-iphone-12-pro-s...,Apple,140900,149900,542,42,MOBFWBYZ5UY6ZBVA,4.5,4 GB
2,"APPLE iPhone 11 Pro (Space Grey, 512 GB)",https://www.flipkart.com/apple-iphone-11-pro-s...,Apple,117900,140300,7088,523,MOBFKCTSRTHRQTFT,4.6,4 GB
3,"APPLE iPhone 11 Pro (Midnight Green, 512 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,117900,140300,7088,523,MOBFKCTSSJCWYGCC,4.6,4 GB
4,"APPLE iPhone 12 Pro Max (Pacific Blue, 256 GB)",https://www.flipkart.com/apple-iphone-12-pro-m...,Apple,130900,139900,580,45,MOBFWBYZ8STJXCVT,4.6,6 GB
...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 128 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,34999,44900,95909,8161,MOBFWQ6BHUEVZPXD,4.5,2 GB
58,"APPLE iPhone SE (White, 128 GB)",https://www.flipkart.com/apple-iphone-se-white...,Apple,34999,44900,95807,8154,MOBFWQ6BJEHMUUZY,4.5,2 GB
59,"APPLE iPhone SE (Red, 128 GB)",https://www.flipkart.com/apple-iphone-se-red-1...,Apple,34999,44900,95909,8161,MOBFWQ6BJTVFKPEJ,4.5,2 GB
60,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB
61,"APPLE iPhone SE (White, 64 GB)",https://www.flipkart.com/apple-iphone-se-white...,Apple,29999,39900,95807,8154,MOBFWQ6BGWDVGF3E,4.5,2 GB

In [49]:
# Get the iPhone with the 3rd highest MRP
third_highest_mrp_iphone = sorted_df.loc[2]

In [50]:
third_highest_mrp_iphone

Product Name                  APPLE iPhone 11 Pro (Space Grey, 512 GB)
Product URL          https://www.flipkart.com/apple-iphone-11-pro-s...
Brand                                                            Apple
Sale Price                                                      117900
Mrp                                                             140300
Number Of Ratings                                                 7088
Number Of Reviews                                                  523
Upc                                                   MOBFKCTSRTHRQTFT
Star Rating                                                        4.6
Ram                                                               4 GB
Name: 2, dtype: object